- Add pytest to test CI
jellyfin/jellyfin-kodi pull request #780
Opened 2023-10-03 05:29 UTC by nwithan8

For whatever reason, the error code from `coverage run` is not surfacing to the Windows runner, and therefore the CI is passing despite several unit tests failing.

Using `pytest` directly does surface the proper error code and halt CI if any tests fail, so that has been added as a step.

`coverage run` is still executed, after `pytest`, to generate the necessary information needed for `coverage xml` and `coverage report`. Because `pytest` runs first, the false-negative tests in `coverage run` will never be encountered.

Closes #777

2023-10-03 17:28 UTC, oddstr13 commented
I think it would be worth testing whether `coverage run` in a separate step properly fails the test
(are tests on windows only failing based on the exit code of the last command?)

2023-10-04 00:51 UTC, oddstr13 requested changes
Looks like my suspicion about only last command's exit code being used is likely correct, see nedbat/coveragepy#1003 and https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

For now, just move `coverage run` to a separate step, naming it `Run tests and collect coverage`, and rename the existing one `Generate coverage reports`.

That should fix pytest not erroring (via coverage) on Windows.
---
We likely have similar issues all over CI, but that can be fixed properly in a separate PR, preferably by having multi-line test steps error out properly.

2023-10-04 01:06 UTC, oddstr13 commented
It is also possible, but not guaranteed that explicitly setting `shell: bash` on the run step(s) fixes the issue.

2023-10-04 01:10 UTC, nwithan8 commented
> It is also possible, but not guaranteed that explicitly setting `shell: bash` on the run step(s) fixes the issue.

I don't believe that would work, trying to run a Bash shell on a Windows machine.

2023-10-04 01:10 UTC, nwithan8 commented
> Looks like my suspicion about only last command's exit code being used is likely correct, see [nedbat/coveragepy#1003](https://github.com/nedbat/coveragepy/issues/1003) and https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
> 
> For now, just move `coverage run` to a separate step, naming it `Run tests and collect coverage`, and rename the existing one `Generate coverage reports`.
> 
> That should fix pytest not erroring (via coverage) on Windows.
> 
> We likely have similar issues all over CI, but that can be fixed properly in a separate PR, preferably by having multi-line test steps error out properly.

Better Google-fu than me!

2023-10-05 19:18 UTC, oddstr13 approved these changes

2023-10-05 19:18 UTC, merged